kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata: {name: minimum, namespace: batch-team}
rules:
  - {apiGroups: [batch], resources: [jobs], verbs: [get], resourceNames: [reconcile-1]}
  - {apiGroups: [batch], resources: [jobs], verbs: [create]}
  - {apiGroups: [batch], resources: [jobs], verbs: [delete], resourceNames: [reconcile-2]}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: {name: minimum, namespace: batch-team}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: minimum}
subjects: [{kind: ServiceAccount, name: job-controller, namespace: batch-team}]
