apiVersion: v1
kind: Namespace
metadata:
  name: kuber-sandbox
  labels:
    kuber.dev/sandbox: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
